import 'package:eva_icons_flutter/eva_icons_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter_movie_app_tmdb/bloc/get_casts_bloc.dart';
import 'package:flutter_movie_app_tmdb/bloc/get_genres_bloc.dart';
import 'package:flutter_movie_app_tmdb/bloc/get_movie_detail_bloc.dart';
import 'package:flutter_movie_app_tmdb/bloc/get_movie_similar_bloc.dart';
import 'package:flutter_movie_app_tmdb/bloc/get_movies_bloc.dart';
import 'package:flutter_movie_app_tmdb/bloc/get_movies_byGenre_bloc.dart';
import 'package:flutter_movie_app_tmdb/bloc/get_now_playing_bloc.dart';
import 'package:flutter_movie_app_tmdb/bloc/get_persons_bloc.dart';
import 'package:flutter_movie_app_tmdb/models/models.dart';
import 'package:flutter_movie_app_tmdb/shared/theme.dart' as Style;
import 'package:flutter_movie_app_tmdb/ui/pages/pages.dart';
import 'package:flutter_rating_bar/flutter_rating_bar.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:page_indicator/page_indicator.dart';

part 'best_movies.dart';
part 'casts.dart';
part 'companies.dart';
part 'genres_list.dart';
part 'genres.dart';
part 'movie_info.dart';
part 'movies_by_genre.dart';
part 'movies_genre.dart';
part 'now_playing.dart';
part 'persons.dart';
part 'similar_movies.dart';
